apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  labels:
    app.kubernetes.io/instance: appset
  name: appset-dev
  namespace: argocd
spec:
generators:
  - git:
      files:
        - path: envs/dev/helloworld.yaml
      repoURL: 'https://github.com/mdouek/argo-appset.git'
      revision: HEAD
  template:
    metadata:
      name: '{{path.basename}}-dev'
    spec:
      destination:
        namespace: '{{path.basename}}'
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        repoURL: 'https://github.com/mdouek/argo-appset.git'
        targetRevision: HEAD
        path: 'charts/{{path.basename}}'
        helm:
          valueFiles:
            - 'envs/dev/{{path.basename}}.yaml'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true