apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  labels:
    app.kubernetes.io/instance: appset
  name: appset-dev
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        files:
          - path: "envs/dev/*.yaml"
        repoURL: 'https://github.com/mdouek/argo-appset.git'
        revision: HEAD
  template:
    metadata:
      name: '{{ index (splitList "." .path.filenameNormalized) 0 }}'
    spec:
      destination:
        namespace: '{{ index (splitList "." .path.filenameNormalized) 0 }}'
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        {{ if .chartRepository }}
        repoURL: '{{ .chartRepository }}'
        targetRevision: '{{ .chartVersion }}'
        chart: '{{ .chartName }}'
        {{ else }}
        repoURL: 'https://github.com/mdouek/argo-appset.git'
        targetRevision: HEAD
        path: 'charts/{{ index (splitList "." .path.filenameNormalized) 0 }}'
        {{ end }}
        helm:
          valueFiles:
            - '../../envs/dev/{{ index (splitList "." .path.filenameNormalized) 0 }}.yaml'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true