apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  labels:
    app.kubernetes.io/instance: appset
  name: appset-dev
  namespace: argocd
spec:
  generators:
    - git:
        files:
          - path: "envs/dev/*.yaml"
        repoURL: 'https://github.com/mdouek/argo-appset.git'
        revision: HEAD
  template:
    metadata:
      name: '{{path.filename}}'
    spec:
      destination:
        namespace: '{{path.filename}}'
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        repoURL: 'https://github.com/mdouek/argo-appset.git'
        targetRevision: HEAD
        path: 'charts/{{path.filename}}'
        helm:
          valueFiles:
            - '../../envs/dev/{{path.filename}}.yaml'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true