apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-applicationset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/mdouek/argo-appset.git
              revision: HEAD
              files:
                - path: "mappings/dev/*/config.yaml"
          - list:
              elements: []
              elementsYaml: "{{ .applications | toJson }}"
  template:
    metadata:
      name: 'dev-{{ .name }}'
    spec:
      project: default
      destination:
        server: 'https://kubernetes.{{ index .path.segments 2 }}.svc'
        namespace: '{{ .namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    spec:
      source:
        repoURL: |
          {{- if .localChart }}
          https://github.com/mdouek/argo-appset.git
          {{- else }}
          {{ .repoURL }}
          {{- end }}
        targetRevision: |
          {{- if .localChart }}
          HEAD
          {{- else }}
          {{ .version }}
          {{- end }}
        chart: |
          {{- if .localChart }}
          null
          {{- else }}
          {{ .chart }}
          {{- end }}
        path: |
          {{- if .localChart }}
          charts/{{ .chart }}
          {{- else }}
          null
          {{- end }}
        helm:
          valueFiles:
          {{- range $valueFile := .valueFiles }}
            - {{ $valueFile }}
          {{- end }}
    {{- if .autoSync }}
      syncPolicy:
        automated:
          prune: {{ .prune }}
    {{- end }}
  syncPolicy:
    preserveResourcesOnDeletion: true
