apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-applicationset
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/mdouek/argo-appset.git
              revision: HEAD
              files:
                - path: "mappings/dev/*/config.yaml"
          - list:
              elements: []
              elementsYaml: "{{ .applications | toJson }}"
  template:
    metadata:
      name: 'dev-{{ .clusterName }}-{{ .name }}'
    spec:
      project: default
      destination:
        name: '{{ .clusterName }}'
        namespace: '{{ .namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    spec:
      sources:
      - repoURL: '{{ .repoURL | default "https://github.com/mdouek/argo-appset.git" }}'
        targetRevision: '{{ .targetRevision | default "HEAD" }}'
        {{- if .chart }}
        chart: '{{ .chart }}'
        path: null
        {{- else }}
        path: '{{ .chartPath }}'
        chart: null
        {{- end }}
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - '$values/envs/dev/environment-values.yaml'
            - '$values/app-values/{{ .name }}-values.yaml'
            - '$values/{{ .valuesFile }}'
      - repoURL: 'https://github.com/mdouek/argo-appset.git'
        targetRevision: HEAD
        ref: values
  syncPolicy:
    preserveResourcesOnDeletion: true
