controller:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
    hostName: jenkins.{{.Values.clusterAnnotations}}
    path: "/"
