controller:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
    hostName: jenkins.{{metadata.annotations.subdomain}}
    path: "/"
