clusterName: in-cluster
applications:
  - name: hello-world
    namespace: hello-world
    chartPath: charts/hello-world
  - name: jenkins
    namespace: jenkins
    repoURL: https://charts.jenkins.io
    chart: jenkins
    targetRevision: 5.6.4
