clusterName: default
address: https://kubernetes.default.svc
applications:
  - name: hello-world
    chartPath: charts/hello-world
    namespace: hello-world
    valuesFile: envs/dev/hello-world-values.yaml
  - name: jenkins
    namespace: jenkins
    valuesFile: envs/dev/jenkins-values.yaml
    repoURL: https://charts.jenkins.io
    chart: jenkins
    targetRevision: 5.6.4
